export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CURRENCY_DATA = 'FETCH_CURRENCY_DATA';
export const FETCH_CURRENCY_DATA_FAILURE = 'FETCH_CURRENCY_DATA_FAILURE';
export const REMOVE_CURRENCY = 'REMOVE_CURRENCY';